# Generated by Django 4.2.4 on 2023-08-04 11:18

from django.db import migrations, models
import month.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_form', month.models.MonthField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=255)),
                ('emp_email', models.EmailField(max_length=254, unique=True)),
                ('emp_id', models.CharField(max_length=10, unique=True)),
                ('emp_phone', models.CharField(max_length=15, unique=True)),
                ('emp_alt_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('department', models.CharField(choices=[('PYTHON', 'PYTHON'), ('JAVA', 'JAVA'), ('EMBEDDED SYSTEMS', 'EMBEDDED SYSTEMS'), ('MATLAB', 'MATLAB'), ('VLSI', 'VLSI')], max_length=25)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ImageField(upload_to='static/profiles')),
                ('cf', models.PositiveIntegerField(default=0)),
                ('address', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
