# Generated by Django 4.2.4 on 2023-08-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('emp_id', models.CharField(max_length=10)),
                ('emp_name', models.CharField(max_length=255)),
                ('earned_leave', models.BooleanField(default=False)),
                ('casual_leave', models.BooleanField(default=False)),
                ('sick_leave', models.BooleanField(default=False)),
                ('maternity_leave', models.BooleanField(default=False)),
                ('leave_reason', models.TextField()),
                ('leavefrom', models.DateField()),
                ('leaveto', models.DateField()),
                ('leave_days', models.PositiveIntegerField()),
            ],
        ),
    ]
